### ISSUE TITLE
Actual Plugin?

### ISSUE THREAD

**Issue by mattpramschufer** [cloudveiltech/wc-subscription-report#1]
Is there an actual plugin for this?  Doesn't appear to have anything in repo besides screen shots and readme.

**Comment by dkwiebe** [comment]
@mattpramschufer That was supposed to get uploaded but it appears we forgot.  I'll take care of that.

**Comment by dkwiebe** [comment]
@mattpramschufer The source code has been uploaded.  We put this together to solve a need for ourselves but feedback and suggestions are welcome.

**Comment by mattpramschufer** [comment]
Awesome thanks!  I'll try it out and probably extend it to suit my needs and contribute back if you would be interested.

**Comment by dkwiebe** [comment]
Yes, we'd definitely be interested.
